/** Declaration file generated by dts-gen */

export function createPackage(src: any, dest: any, callback: any): any;

export function createPackageFromFiles(src: any, dest: any, filenames: any, metadata: any, options: any, callback: any): any;

export function createPackageWithOptions(src: any, dest: any, options: any, callback: any): any;

export function extractAll(archive: any, dest: any): any;

export function extractFile(archive: any, filename: any): any;

export function listPackage(archive: any): any;

export function statFile(archive: any, filename: any, followLinks: any): any;

export function uncache(archive: any): any;

export function uncacheAll(): void;

export function validatePackage(archive: any): void;

export namespace createPackage {
    const prototype: {
    };

}

export namespace createPackageFromFiles {
    const prototype: {
    };

}

export namespace createPackageWithOptions {
    const prototype: {
    };

}

export namespace extractAll {
    const prototype: {
    };

}

export namespace extractFile {
    const prototype: {
    };

}

export namespace listPackage {
    const prototype: {
    };

}

export namespace statFile {
    const prototype: {
    };

}

export namespace uncache {
    const prototype: {
    };

}

export namespace uncacheAll {
    const prototype: {
    };

}

export namespace validatePackage {
    const prototype: {
    };

}

